# Generated by Django 5.0.7 on 2024-08-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pv', '0002_appeloffre_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeloffre',
            old_name='numero_lot',
            new_name='lots',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='lieu_livraison',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='quantite_lot',
        ),
    ]
